# Generated by Django 3.2.9 on 2021-11-19 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='')),
                ('applied_date', models.DateField()),
                ('Status', models.CharField(default='Selected/Rejected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentProvideruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('workplace', models.CharField(max_length=100, null=True)),
                ('workarea', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('Status', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobseekeruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sendresponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.employmentprovideruser')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.employee_jobs')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.jobseekeruser')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Title', models.CharField(max_length=100)),
                ('salary', models.FloatField(max_length=20)),
                ('Job_description', models.CharField(max_length=300)),
                ('workplace_images', models.FileField(null=True, upload_to='')),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('date_of_creation', models.DateField()),
                ('Employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.employmentprovideruser')),
            ],
        ),
        migrations.AddField(
            model_name='employee_jobs',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.jobseekeruser'),
        ),
        migrations.AddField(
            model_name='employee_jobs',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.job'),
        ),
    ]
