# Generated by Django 3.2.9 on 2021-11-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendresponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.employmentprovideruser')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.employee_jobs')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.jobseekeruser')),
            ],
        ),
    ]
