# Generated by Django 3.2.9 on 2021-11-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeruser',
            name='edu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseekeruser',
            name='jobd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseekeruser',
            name='sal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
