# Generated by Django 3.2.9 on 2021-11-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_sendresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_jobs',
            name='Status',
            field=models.CharField(default='Selected/Rejected', max_length=20),
        ),
    ]
